server:
  port: 8200

#默认使用配置
spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 300MB

# Thymeleaf 配置
  thymeleaf:
    cache: false
    prefix: classpath:/thymeleaf/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

logging:
  level:
    com.tgpms.web: debug

